from src.util.json_util import ConfigSingleton
import json
from cryptography.fernet import Fernet,InvalidToken
from src.objects.symbol import kicad_symbol
import pyodbc
import os
from abc import ABC, abstractmethod
from src.events.eventReceiver import EventReceiver
from blinker import Signal

class DataBaseConnector(ABC):
    _instance = None  # Statická proměnná pro uchování instance

    def __new__(cls):
        """Singleton pattern"""
        if cls._instance is None:
            cls._instance = super(DataBaseConnector, cls).__new__(cls)            
        return cls._instance
     
    def __init__(self):

        self.connection = None
        self._connected = False

    def saveCmd(self, sender, **kwargs):

        obj_symbol: kicad_symbol = kwargs.get("symbol") # Kicad symbol sended by event
        
        print("Save symbol ERP data to database")
        ConnectedDB, CursorTestDb, ConnectionTestDb = self.connect()
        if (not ConnectedDB):
            print("Cannot connect to remote db")
            return 
        
        result = self.send_query(r"SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'TabKmenZbozi';")
        
        
        result = self.send_query(r"SELECT MAX(RegCis) AS MaxRegCis FROM TabKmenZbozi WHERE SkupZbo = 320")
        maxregcis = result[0][0]
        print (maxregcis)
        number = int(maxregcis)
        number = number +1 
        print(number)
                
        # create new item in db         
        self.copy_last_record('TabKmenZbozi',maxregcis)

        #Update record by symbol        
        self.update_record_by_kicad_symbol('TabKmenZbozi', number, obj_symbol)

        # Close db connection
        self.close()  

        # Update symbol
        obj_symbol.propertiesFinal['ERP']['value'] = "320/" + f"{number:06}"
        self.item_DbSaveFinished.send(self, symbol=obj_symbol)


    @abstractmethod
    def get_connection_info(self) -> dict:
        """Child musí vrátit dict s údaji pro připojení"""
        pass

    def get_password(self):
        # Tvůj šifrovací klíč (musí být stejný jako při šifrování)
        with open("crypto.key", "rb") as key_file:
            key = key_file.read()
       
        cipher = Fernet(key)     
        # Dešifrování hesla
        return cipher.decrypt( self.config.get('helios_app_password').encode()).decode()


    @property
    def connected(self):
        return self._connected

    def __del__(self):
        try:
            if self.connection and self._connected:
                self.connection.close()
        except Exception as ex:
            print(f"Error closing connection in Helios destructor: {ex}")

    def get_connection(self):
        return self.connection

    def close(self):
        try:
            if self.connection and self._connected:
                self.connection.close()
            self._connected = False
        except Exception as ex:
            print(f"Error closing connection: {ex}")


    def send_query(self, sql_query, values=None):
        try:
            cursor = self.connection.cursor()
            if values is None:
                cursor.execute(sql_query)
            else:
                cursor.execute(sql_query, values)

            # SELECT dotazy mají description, INSERT/UPDATE/DELETE ne
            if cursor.description:
                rows = cursor.fetchall()
                cursor.close()
                return rows
            else:
                self.connection.commit()
                rc = cursor.rowcount
                cursor.close()
                return rc

        except Exception as e:
            print("Database error:", e)
        return None

    
    def update_record_by_kicad_symbol(self, tablename, RegCis, symbol:kicad_symbol):
        sql = f"""
            UPDATE {tablename}
            SET Nazev1 = ?, Nazev2 = ?, Poznamka = ?, Nazev3 = ?, Nazev4 = ?, Aktualni_Dodavatel = ?, Vyrobce = ? 
            WHERE RegCis = ? AND SkupZbo = 320
        """

        nazev1 = symbol.propertiesFinal['ERP_Title1_czech']['value']
        nazev2 = symbol.propertiesFinal['ERP_Title2_english']['value']
        sym_val = symbol.propertiesFinal['Value']['value']
        #producer = symbol.propertiesFinal['ERP_Manufacturer_Name']['value']
        #akt_dod = symbol.propertiesFinal['ERP_Supplier_Name']['value']
        producer = None
        akt_dod = None
        poznamka = symbol.propertiesFinal['ERP_Summaries']['value'] + "\n" + symbol.propertiesFinal['ERP_link1']['value'] + "\n" + symbol.propertiesFinal['ERP_link2']['value']
        res = self.send_query(sql, [nazev1, nazev2, poznamka, sym_val,sym_val, akt_dod, producer, RegCis])
        return res
        #SELECT TOP(10) RegCis,Nazev1,Nazev2,Nazev3,Nazev4 FROM TabKmenZbozi WHERE RegCis > 000072

    def copy_last_record(self, tablename, registrationnr):
        sql = f"""
        DECLARE @TableName sysname = N'{tablename}';
        DECLARE @SourceID INT;
        DECLARE @NewRegCis NVARCHAR(6);
        DECLARE @colsSelect NVARCHAR(MAX);
        DECLARE @SkupZbo INT;

        -- 1) Vyber poslední řádek podle RegCis a SkupZbo
        SELECT TOP 1 @SourceID = ID, @SkupZbo = SkupZbo
        FROM {tablename}
        WHERE RegCis = ? AND SkupZbo = 320
        ORDER BY ID DESC;

        IF @SourceID IS NULL
        BEGIN
            RAISERROR('Záznam s RegCis = %s nebyl nalezen.', 16, 1);
            RETURN;
        END

        -- 2) Vyber všechny sloupce kromě identity a RegCis
        SELECT @colsSelect = STRING_AGG(QUOTENAME(name), ', ')
        FROM sys.columns
        WHERE object_id = OBJECT_ID(@TableName)
          AND is_identity = 0
          AND is_computed = 0
          AND system_type_id <> 189
          AND name <> 'RegCis';

        -- 3) Spočítej nový RegCis (unikátní pro SkupZbo)
        SELECT @NewRegCis = RIGHT('000000' + CAST(MAX(TRY_CAST(RegCis AS INT)) + 1 AS VARCHAR(6)), 6)
        FROM {tablename}
        WHERE SkupZbo = @SkupZbo;

        -- 4) Vlož pouze jeden řádek
        DECLARE @sql NVARCHAR(MAX) = '
        INSERT INTO ' + QUOTENAME(@TableName) + ' (RegCis, ' + @colsSelect + ')
        SELECT @NewRegCis, ' + @colsSelect + '
        FROM ' + QUOTENAME(@TableName) + '
        WHERE ID = @SourceID';

        EXEC sp_executesql 
            @sql,
            N'@SourceID INT, @NewRegCis NVARCHAR(6)',
            @SourceID = @SourceID,
            @NewRegCis = @NewRegCis;
        """

        return self.send_query(sql, (registrationnr,))


        
        
        

    def _maybe_decrypt(self, token: str) -> str:
        """
        Pokud je token Fernet token (např. 'gAAAAAB...'), pokusí se jej rozšifrovat.
        Jinak vrátí token nezměněný.
        """
        if not token:
            return token

        # jednoduchá heuristika: fernet tokeny většinou začínají 'gAAAA'
        if not isinstance(token, str) or not token.startswith("gAAAA"):
            return token

        # získej key buď z konfigurace nebo z environment proměnné
        # *Uprav podle toho, kde máš uložený klíč*:
        key = "AGFVbAy4SscjhPC1Eboj_D0YCBHte4K7mn2BXVlsC-4="  # doporučené
        # nebo např. key = ConfigSingleton().get("helios_fernet_key")

        if not key:
            # pokud nemáme klíč, raději vrať token (nepokusíme se dešifrovat)
            # nebo případně vyhoď chybu podle potřeby
            return token

        try:
            f = Fernet(key.encode() if isinstance(key, str) else key)
            decrypted = f.decrypt(token.encode())
            return decrypted.decode('utf-8')
        except (InvalidToken, ValueError) as e:
            # není to platný Fernet token nebo špatný klíč -> vrátíme originál
            # případně zde můžeš logovat warning
            return token   
        
       
          
        
        
        
        
        
        


    def get_table_defs(self, table_name):
        cursor = self.connection.cursor()
        cursor.execute("""
            SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE, COLUMN_DEFAULT
            FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_NAME = ?
        """, (table_name,))

        columns = cursor.fetchall()
        if not columns:
            print(f"Tabulka {table_name} neexistuje.")
            exit()

        column_defs = []
        for col in columns:
            col_def = f"{col[0]} {col[1]}"

            # Přidání maximální délky pro typy, které ji podporují (např. varchar)
            if col[1] in ['varchar', 'char', 'nvarchar', 'nchar'] and col[2]:
                if col[2] > 0:  # Ošetření nulové délky
                    col_def += f"({col[2]})"

            # Kontrola, zda je sloupec NOT NULL
            if col[3] == 'NO':
                col_def += " NOT NULL"

            # Kontrola pro DEFAULT hodnotu, která není None nebo 0
            if col[4] and col[4] != '0':  # Ošetření default hodnoty '0' nebo None
                col_def += f" DEFAULT {col[4]}"

            column_defs.append(col_def)

        return ", ".join(column_defs)


            
        
    def connect(self) ->  tuple[bool, pyodbc.Cursor]:
        info = self.get_connection_info()
        connection_string = (
            f"DRIVER={{SQL Server}};"
            f"SERVER={info['ip']};"
            f"DATABASE={info['db']};"
            f"UID={info['login']};"
            f"PWD={info['password']};"
            f"Workstation ID={info['workstation']};"
        )
        try:
            self.connection = pyodbc.connect(connection_string)
            self._connected = True
            print(f"Connected\n")
            return True, self.connection.cursor(), self.connection
        
        except Exception as ex:
            print(f"Function Helios::Connect error: {ex}")
            if self.connection:
                self.connection.close()
            return False, None, None
        
    def registerEventReceiverSaveCmd(self, signal_save):
        self.receiverSave = EventReceiver(signal_save, self.saveCmd)

    def set_signal_DbSaveFinished(self, signal: Signal):
        self.item_DbSaveFinished = signal
      
class HeliosDB(DataBaseConnector):
    def get_connection_info(self):
        config = ConfigSingleton()
        raw_password = config.get("helios_app_password")

        password = self._maybe_decrypt(raw_password)
        return {
            "login": config.get("helios_app_login"),
            "ip": config.get("helios_ip_address"),
            "db": config.get("helios_db_catalog"),
            "password": password,
            "workstation": os.environ.get("COMPUTERNAME", "Unknown")
        }
    
    #def get_

#    def copyTable(self):
         

"""
('TabPravaObecPrehled',)
('TabIKJNaPH',)
('TabJCDIm',)
('TabUniImportDenikVerze',)
('TabDynVazbaAtributy',)
('TabUpom',)
('TabVSouhlasyKategAtr',)
('TabMzP104CzDruhCinnostiStredisko',)
('TabDenRizeniDZ',)
('TabPaletySSCC',)
('TabFIAAVVykazDefinicePlan',)
('TabPlatTuzVzor',)
('TabSTDLeaPomerKoef',)
('TabUniImportOrgVerze',)
('TabDuchod',)
('TabAutoUctovaniPar',)
('TabMzMesUzavAkce',)
('TabMzdPojRokDobyZam',)
('TabTypPostupVyrProfese',)
('TabDavka',)
('TabInfoPanelDetail',)
('TabSZUzaverkaPolozky',)
('TabZkZadaniUcto',)
('TabDosleObjRVStin01',)
('TabPrKVazby',)
('TabZkPravidlo',)
('TabHlavniStrom',)
('TabStavSkladu',)
('TabAltKVazby',)
('TabFIAVDataParamRadaUctenky',)
('TabCisUcSalSkFA',)
('TabELDPR',)
('TabSMSOdeslano',)
('TabPomocnicekZakazany',)
('TabIVozidlo',)
('TabPartneriKON',)
('TabFIAAVykazDefiniceNadurovne',)
('TabCisOrgImp',)
('TabFIAWebGroups',)
('TabSbornikDef',)
('TabUctenkaR',)
('TabPoznKontJed',)
('TabZamVlastnik',)
('TabURL',)
('TabEvidRozpracOper',)
('TabFIAVSestavaSbornik',)
('TabWFPrava',)
('TabMaTechParam1',)
('TabKvazbyImp',)
('TabPravaEvPSch',)
('TabFIAAVykaz',)
('TabKontrHlaB2',)
('TabPravaRadyZakazModif',)
('TabZamVyp',)
('TabUzivAtrPracHod',)
('TabUmisteniPrijem',)
('TabIZasOdbH',)
('TabAdvKPDavky',)
('TabUctenkaUzaverka',)
('TabGprCinnostiVyrPerZdroju',)
('TabISDSazT',)
('TabCzmeny',)
('TabBankSpSchvOsobyVazba',)
('TabRefundaceH',)
('TabPokladnaStorno',)
('TabUniImportDenikFormat',)
('TabFIADict',)
('TabZmenovyLOG',)
('TabMzIscpSkOrg',)
('TabJCDPohybyOpatreniVAZ',)
('TabMzP104CzRadky',)
('TabPrjVAktivity',)
('TabQMSLog',)
('TabFiaWebJOINs',)
('TabUniImportOrgFormat',)
('TabRozkopIDs',)
('TabCPracoUzivAtr',)
('TabPrjNeperSRC',)
('TabESServiceMessages',)
('TabCelSaz',)
('TabQMSOpakovaneUkoly',)
('TabDosleObjRVStin02',)
('TabZkZadVypDef',)
('TabObecnaVazba',)
('TabMzHlaseniKonecPN',)
('TabKontrVykB3',)
('TabSKDanDluznici',)
('TabSTDStavUctuPom',)
('TabCisUctSalSkFADef',)
('TabVSouhlasyUcelyZpr',)
('TabMzKontoPrescB',)
('TabKalkRozKD',)
('TabPSDefNavCisP',)
('TabStrom',)
('TabCakoCisSklady',)
('TabMzdPojRokDobyStat',)
('TabNemocPredIQ',)
('TabQMSCisAuditKapitolyNormy',)
('TabSkupinyZboziImp',)
('TabSkupKont',)
('TabPodmenuDoplnku',)
('TabNCTSVyslVAZ',)
('TabSzDokladyZbozi',)
('TabLimitObratu',)
('TabFIARozpusteniRezii',)
('TabGprVzorProjektyEtapy',)
('TabPlatZahrVzor',)
('TabSMSPrijato',)
('TabFIAVUkazatelSbornik',)
('TabFMEAPricinyVady',)
('TestPerformanceTable',)
('TabFIAWebDimensions',)
('TabPrjKapacPlanOdebraneUkoly',)
('TabMzMesDochKodyMS',)
('TabZamVzdImp',)
('TabIKontTyp',)
('TabSazbyDPHZboAVA',)
('TabPravaCrossTab',)
('TabInvPerson',)
('TabSaldoFA',)
('TabKPPlatnostKmenZbo',)
('TabMzdDanSkArch',)
('TabFIAVSestavaPlan',)
('TabRozkopFK',)
('TabFIAEVUcJednKonsolVykazParam',)
('TabCakoPar',)
('TabUmisteniVydej',)
('TabIZasBC',)
('TabFIAVWebGroupsWebUsers',)
('TabDosleObjRVStin03',)
('TabZkRezie',)
('TabGenMzdyVysl_2',)
('TabRefundaceP',)
('TabMzNastupPPMS',)
('TabMzExportCSKons',)
('TabUniImportOrgUp',)
('TabKJUcastZam',)
('TabIDopMistNakVyk',)
('TabSTDDenikStandardPom',)
('TabKPLHlavLogVysledek',)
('TabMzDanPrehledKumul',)
('TabPenFak',)
('TabMzP104CzAtr',)
('TestPerformanceTableLog',)
('TabPrjVAktivPozice',)
('TabFIAAVykazDefinicePLG',)
('TabStatniSvatky',)
('TabStavSkladu_EXT',)
('TabMzMesUzavCfg',)
('TabPrikazMzdyAZmetky',)
('TabCKoop',)
('TabInfoPanelDetailUsers',)
('TabMzDzdpnNotifSk',)
('TabFIAAVerzeVykazu',)
('TabCisUctDef',)
('TabGprCinnostiSkupinNepZdroju',)
('TabMzPraxeUzn',)
('TabISezAdr',)
('TabKontrVykC1',)
('TabGprNepZdroje',)
('TabPravaAdvKapacPlan',)
('TabNCTSUdalostiKontejnery',)
('TabDokZboDodatek',)
('TabFIAVUkazatelClenSbornik',)
('TabPohSNRadek',)
('TabPlatTuzVzorR',)
('TabUniImportZak',)
('TabDSDruhD',)
('TabDosleObjVyrCis20',)
('TabPomKonsolPrehled',)
('TabCakoZurnal',)
('TabAdvKPProfese',)
('TabFIAWebRights',)
('TabMzDohadnePolSkR',)
('TabUctenkaUzaverDok',)
('TabDosleObjR02',)
('TabISubstrat',)
('TabVyporadaniSK408',)
('TabFIASestava',)
('TabVSouhlasyTypyUcelyZpr',)
('TabFIABVzorceIns',)
('TabMaTechParam2',)
('TabKontrHlaB3',)
('TabINabidka',)
('TabMzdCisloExportDef',)
('TabMzP204Sk',)
('TabKontrolyEkoLog',)
('TabDosleObjROriginal01',)
('TabBankSpSchvDuvody',)
('TabNCTSPohybyVyslVAZ',)
('TabKJUcastOrg',)
('TabUzaverkyPokladny',)
('TabMzZPDavka590Zam',)
('TabGprVzorUlohy',)
('TabMzUnpSkPocet',)
('TabFIAEDenikSourceMatka',)
('TabMzJubileaTypy',)
('TabPrikazPlanNaklady',)
('TabKvazby_EXT',)
('TabRozkopXX',)
('TabBankVypisH',)
('TabMJVztah',)
('TabSkladPrijmySN',)
('TabVStavUmisteni',)
('TabIParita',)
('TabZamPeceODetiSk',)
('TabMJImp',)
('TabRoleUziv',)
('TabFIARozpusteniReziiDetail',)
('TabUctenkaRPHlav',)
('TabISDSazO',)
('TabMzDanPrehledParams',)
('TabKJUcastKontakt',)
('SDServer_Pracoviste',)
('TabKPLNavAkce',)
('TabCisUcSalSk',)
('TabKPPlatnostOrg',)
('TabInventuraLog',)
('TabPrjKategorieCB',)
('TabVDenikSaldoPrehledy',)
('TabDruhyUzivKurzu',)
('TabPrikazVCPrevodPolotov',)
('TabKontrHlaC',)
('TabCelSazSZOld',)
('TabPrjTasks',)
('TabMzENeschopenkySk',)
('TabDosleObjVyrobniZmeny',)
('TabZamJmeImp',)
('TabExterniZdroj',)
('TabVSvsSpoDObjR',)
('TabSKDanSubjRegSD',)
('TabNCTSUdalostiZavery',)
('TabEvidRozpracOperR',)
('TabKodyZmenUP',)
('TabFIADataDimStruktura',)
('TabPaletySSCCPolozky',)
('Gatema_ManJedPol',)
('TabUniImportZakVerze',)
('TabVSkoleniZam',)
('TabPomKonsolPrehledUcty',)
('TabSkupZboOrgSlevy',)
('TabVDruhPoRadaUctenek',)
('TabFIAWebDevices',)
('TabFIAAObdobiProVykazy',)
('TabGprCinnostiNepZdroju',)
('TabDzPPoR',)
('TabUctenkaVoucherPlatby',)
('TabKJUcastKOs',)
('TabELDPRZaklady',)
('TabZdrojeOsUdaju',)
('TabUkolyOutlookKal',)
('TabDSHromadnyKontakt',)
('TabSalSk',)
('TabFIAAPopisneUdaje',)
('TabUhrady',)
('TabToDoList',)
('TabMzAntivirusDefinice',)
('TabClaWorkflow',)
('TabIKalkVzHl',)
('TabPohybySN',)
('TabPravaGraphDef',)
('TabPostup',)
('TabZemeRefH',)
('TabCSmeny',)
('TabFIAVRozpusteniReziiCisloUcet',)
('TabISDSazSnizeni',)
('TabMaStdUcto',)
('SDServer_Users',)
('TabNakladovyOkruh',)
('TabDefSes',)
('TabFiaDataDimPohled',)
('TabVStin',)
('TabKvazbyImp_EXT',)
('TabPlanSkoleni',)
('TabPlanImp',)
('TabRozkopPol',)
('TabAutoUctovaniErr',)
('TabDSPruvDokl',)
('TabDosleObjRVStin20',)
('TabINabKal',)
('TabMzSloz',)
('TabVyporadaniSK407',)
('TabKontrolyEkoPar',)
('TabUctenkaUzaverDPH',)
('TabNCImp',)
('TabNCTSUdalostiSPZ',)
('TabAutoImpKLParam',)
('TabPrjPerSRCPrava',)
('TabMOSS',)
('TabFIAAVykazDefinice',)
('TabUniImportZakFormat',)
('TabUkolOpakZam',)
('TabMzZPDavka514Org',)
('TabVDenikKH',)
('TabCelSazOld',)
('TabPrjTimeSheet',)
('TabSEServiceAttachments',)
('TabPravaSbornik',)
('TabFIAWebLayouts',)
('TabCisNCAVA',)
('TabMzIsp2014Cz',)
('TabSmlOInkasu',)
('TabMaDrPo',)
('TabFIAVSestavaRozpusteniRezii',)
('TabISdSazN',)
('TabGprVzorPerZdroje',)
('TabAlterKZ',)
('TabVKonJedDruhDokZbo',)
('TabFIADataDimPrvek',)
('TabNCTSPohyby',)
('TabSkupMS',)
('TabDefTisk',)
('TabOblibeneDB',)
('TabInterniHlasky',)
('TabZustCelSklad',)
('TabSazbyDPHPoznKDokl',)
('TabSkupinyZbozi_EXT',)
('TabEMailProfil',)
('TabCisUct',)
('TabDokumHistorie',)
('TabMzP204SkAtr',)
('TabMzDvzUdaje',)
('TabVerzeAPrava',)
('TabMzPraxeKrac',)
('TabIKalkVzPo',)
('TabBankSpSchvZastup',)
('TabIVozPrerazeni',)
('TabDruhPoDef',)
('SDServer_Konfig',)
('TabUkolyAktivityHistorie',)
('TabMaLokCFG',)
('TabQMSKlasVyznamVady',)
('TabMzZmenyUP',)
('TabMzKalendarDny',)
('TabVStornoSH',)
('TabAutomatizaceDefinice',)
('TabNCTSPohybyAltMJ',)
('TabAkcePoklProdZbo',)
('TabRozkopErr',)
('TabMzOznameniUP',)
('TabKontrHlaDPHCasti',)
('TabVUPlneniKonJed',)
('TabMzVPobockyZdrPoj',)
('TabMajPrnNajSml',)
('TabNCTSXMLCHB',)
('TabCIMZbozi',)
('TabDosleObjROriginal02',)
('TabMzPrilohaDNPRO',)
('TabGprNavazneDoklady',)
('TabZkTyp',)
('TabMzKalendarImp',)
('TabDenRefP',)
('TabMzIspvCzOrg',)
('TabKontrVykC2',)
('TabMzExportCSKonsMS',)
('TabEmailLog',)
('TabAdvKPLogVypoctu',)
('TabIStNorma',)
('TabDBHelios',)
('TabFIAADenikPAP',)
('WHS_TabTS_Kalendar',)
('TabVariantZbozi',)
('TabPersUchazecVzd',)
('TabGprOcenMatZdroju',)
('TabClaCitZbo',)
('TabDruhPokladen',)
('TabKPPlatnostDruhDokZbo',)
('TabEvidRozpracOperRozpisZam',)
('TabDosleObjH03',)
('TabPoznZak',)
('TabMzP104CzMS',)
('TabFIAVDataDimPrvekCisOrg',)
('TabRenameAtr',)
('TabNvazbyImp',)
('TabPNDSK',)
('TabUniImportUcty',)
('TabDosleObjStav',)
('TabDenik',)
('TabIPopt',)
('TabMajPrnNajSmlDet',)
('TabClaEcitOld',)
('TabToDoListResitele',)
('TabISezMist',)
('TabBankVypisRVazbaCisloRadkyDeniku',)
('TabKodyRefundace',)
('TabRadyOdchylek',)
('TabFIAAColorSchema',)
('TabGDPRPozadavky',)
('Gatema_SDDoklady',)
('TabDefTabUzivTabulka',)
('TabAutoImpKLBanky',)
('TabDefSesPar',)
('TabPohSNCastky',)
('Gatema_KategorieManJed',)
('TabEMCS',)
('TabExtKom',)
('TabPlanZdrojOZ',)
('TabFIAWebPages',)
('TabUctenkaUzaverFU',)
('TabVKmenVarianty',)
('TabMzHlKonecPNDoby',)
('TabIVagTyp',)
('TabStromCFG',)
('TabNCTSZemReceptury',)
('TabFIAVDataDimPrvekStrom',)
('TabPaletySSCCVazby',)
('TabFIAEParamKonsol',)
('TabHighNotif',)
('TabNCTSPohybyChemickeLatky',)
('TabUniImportUctyVerze',)
('TabStavSkKalkRoz',)
('TabAdvKPUseky',)
('TabPrikazZdrojOZ',)
('TabFIAData',)
('TabPrikazKalkNaklady',)
('ASGC_TabKvazbyImp',)
('TabLogZajisteniDPH',)
('TabStrukKusovZV',)
('TabSNkDatuAkt',)
('TabFIACDefinice',)
('TabISDArch',)
('TabVEmailLogKontakt',)
('Gatema_SDZdrojData',)
('TabVKatKonJedUkoly',)
('TabMaLok',)
('TabCisMzSl',)
('TabDefFormSestavyH',)
('TabPrikazMzdyAZmetkyGenPZ',)
('TabMajPrnNajSmlOdpis',)
('TabPrikazZdrojVyrPlan',)
('TabZkUkNavaznaHodnota',)
('TabSHSKDruhaCast',)
('TabISezSpol',)
('TabZakazaneSN',)
('TabBankAPISp',)
('ImportDodavatele',)
('TabCisUctSkKont',)
('TabCVzorcuSpotMat',)
('TabPlatUdajeFaLog',)
('TabPolozkyPoklStorno',)
('TabCisUkolSazeb',)
('TabUctenkaRPUrov',)
('TabCelZarukyVazbaNNReqSent',)
('TabNCTSLRNx',)
('TabIVagSkup',)
('TabKurzListCM',)
('Tab1NUKod',)
('TabMaInv',)
('TabFIAVDataDimPrvekZakazka',)
('TabPaletySSCCVC',)
('TabCMR',)
('TabPrjTasksEd',)
('TabZboziDodavatel',)
('TabDISPReqSent',)
('TabDSPruvPol',)
('TabCisUctDefImp',)
('TabMzMesVykazSPOrg',)
('TabFIAUkazatelClenTables',)
('TabVUctenkaPokladna',)
('TabNCTSDokPreVAZDocPouAltMJ',)
('TabMaticeUcto',)
('TabSzCisKZ',)
('TabSaldoArch',)
('TabMzDefRozpad',)
('TabKontrVykD1',)
('TabVelikostEditOkna',)
('TabMzP1a04Cz',)
('TabVEmailLogCisKos',)
('Gatema_SDDokumenty',)
('TabPohybyZboziSD',)
('TabVKonJedRadyPrikazu',)
('TabDuchSporRzPol',)
('TabOblibeneNastav',)
('TabUniImportUctyFormat',)
('TabZpusobZajDObj01',)
('TabNabRad',)
('TabPracovniPozice',)
('TabDochazkaNavrhy',)
('TabISezMJ',)
('TabBarCodeZboImp',)
('TabNCTSAddCodes',)
('TabStromSkKont',)
('TabCOdchylek',)
('TabGprVzorNepZdroje',)
('TabRDefSes',)
('TabFIAVDataDimPrvekNakladovyOkruh',)
('TabCisKOs',)
('TabMzPrepStavy',)
('TabFIAAVCisUctVykazDefinice',)
('TabCelZarukyPripady',)
('TabSkoliciAkceH',)
('TabCastiKHCisUct',)
('TabPrjExpenseSheet',)
('TabFIAUkazatelClenJoin',)
('TabUmistPrijemVC',)
('TabMzIspCz',)
('TabDosleObjROriginal03',)
('TabCzIsco',)
('TabNCTSXMLPopis',)
('TabPersUchazecPracPozice',)
('TabScontoFaktury',)
('TabVEmailLogCisOrg',)
('Gatema_SDBaleni',)
('TabRadyVariant',)
('TabDynVazbaPrava',)
('TabPravaFiltr',)
('TabFIAKonst',)
('TabINHM',)
('TabEvidRozpracOperRZmetky',)
('TabDefZpravDodatek',)
('TabInvVyroby',)
('TabMOSSPolozky',)
('TabLayoutDefUsers',)
('TabIVznikZajmu',)
('TabToDoListSeznamID',)
('TabVstupniDokladySN',)
('TabKontaD',)
('TabPlatUdajeZadrzneLog',)
('TabUkoly',)
('TabMzIscpSkZam',)
('TabKPPlatnostRadyPrikazu',)
('TabQMSOrganizace',)
('TabRadekUKod',)
('TabQMSKlasPravdepodVyskytuVady',)
('TabFIAVDataDimPrvekIVozidlo',)
('TabNastavKJDok',)
('TabDokladyZboziQRFa',)
('TabFIAVRozpusteniReziiCisloUcetZakladna',)
('TabKategCenPP',)
('TabOblibFiltr',)
('TabFIAWebReports',)
('TabDefISP',)
('TabZkUkazatel',)
('TabPoklFIFO',)
('TabIRelHl',)
('TabMaFaZbozi',)
('TabPouzitiHeliosu',)
('TabKontrVykD2',)
('TabRozucMS',)
('TabGprUlohyNepZdroje',)
('TabFIAAReport',)
('Tab1NPomSkupinyZbozi',)
('TabSzMultiLog',)
('TabVEmailLogCisZam',)
('TabZeFADPH',)
('TabAutoImpKLProtokol',)
('TabVDenikSaldoFA',)
('TabFIAAVVozidloVykazParam',)
('TabIZasilkaVag',)
('TabMaInfo',)
('TabPostupUkony',)
('TabNedavne',)
('TabUniImportKmen',)
('TabMzdOdpPolMes',)
('TabSkupRegKHDPH',)
('TabSTDUctovyRozvrhStandard',)
('TabMzP204SkMS',)
('TabVKontaSkupKontO',)
('TabNotifikace',)
('TabNCTSZajDlParagraf',)
('TabMzKontoPresc',)
('TabCiselnikCinnosti',)
('TabVyrCSImp',)
('TabDruhPokladenImp',)
('TabSzUmisteniKatZv',)
('TabMaPohDproSk',)
('Gatema_SDScanData',)
('TabMaInvCK',)
('TabMzKonsDNP',)
('TabFIAVDataDimPrvekCisZam',)
('TabPaletySSCCSkupinyOrganizace',)
('TabDefFormSestavyR',)
('TabVDenikMOSS',)
('TabVKonJedDokZbo',)
('TabPrikazMzdyAZmetky_EXT',)
('TabRozkopErrDetail',)
('TabRetezDokladuNastav',)
('TabFIADenikId',)
('TabObdobiDPH',)
('TabIRelPo',)
('TabNCAVA',)
('TabSTDLeaPohybDetail',)
('TabBankSpojeniArch',)
('TabMzIsp2014CzAtr',)
('TabDokladyZbozi',)
('TabIntrUnits',)
('TabSoudky',)
('TabSaldoFACM',)
('TabSaldoCM',)
('TabFIAAVZamestnanecVykazParam',)
('TabFIAAVVykazParamObdobiStavu',)
('TabZmenyDBObjektu',)
('TabFIADenikPreuctRezii',)
('TabEUR',)
('TabCenyPracovnichPozic',)
('TabKontaKO',)
('TabMzDefRozpadPol',)
('TabNCTSXMLPravidla',)
('TabVStromDruhDZ',)
('TabZbyvajiciSN',)
('Gatema_SDLogPol',)
('TabCVariant',)
('TabFIAVDataDimPrvekCisUctDef',)
('TabZadrzne',)
('TabVDokPoklUhr',)
('TabHighNotifLog',)
('TabBIDMainTree',)
('TabMOSSSluzby',)
('TabPravaSklad',)
('TabDosleObjRada',)
('TabPlanPrNVazby',)
('TabVDBRozkopCis',)
('TabQRKod',)
('TabAdvKPVypocty',)
('TabMzdOdpPol',)
('TabDefaultFiltr',)
('ASGc_Dochazka',)
('TabFIAAStavUctuPAP',)
('TabCisOrg_EXT',)
('TabEDocEngineNastaveni',)
('TabIDisponent',)
('TabFIACPlanSkutRadek',)
('TabAVAReceivedInvoiceSummationAmounts',)
('TabPersUchazecZdrojCis',)
('TabGprVzorMatZdroje',)
('TabVyrCisPrP',)
('TabPokladna',)
('TabPravaZakRada',)
('TabQMSParHodnoceni',)
('TabEvPSchranky',)
('TabNCTSZaj',)
('TabFIAAVVykazParamObdobiVykazuDetail',)
('TabUniImportKmenVerze',)
('TabGDPRKategorieAtributu',)
('TabISDSazNSKa',)
('ImportSalda',)
('TabZpusobZajDObj02',)
('TabFIAPreuctovaniRezii',)
('TabDopKod',)
('TabMaFaSablony',)
('TabZajisteniDPHWSKonfig',)
('TabFIAWebApplications',)
('TabUctenkaHardware',)
('TabMaFaZboziPol',)
('TabUctenkaRPTlac',)
('TabSzUzaverkaKZ',)
('TabDosleObjNavazTxt01',)
('Gatema_SDLogVC',)
('TabFiaWebData',)
('TabZKalkulace',)
('TabMzCerpaniPrescB',)
('TabIVozStav',)
('TabFIAVDataDimPrvekCisMzSl',)
('TabKontakty',)
('Gatema_PohybManJed',)
('TabOZPoznamky',)
('TabInvPolozka',)
('TabBarCodeZbo',)
('TabVDSPruvDokl',)
('TabIZasRadDispon',)
('TabMzP204SkOrg',)
('TabVyrCK',)
('TabDosleObjNavazDok01',)
('TabIZasilka',)
('TabSoudkyPoradi',)
('TabEETTrzba',)
('TabMzZmenyPost',)
('TabPersUchazecZnalosti',)
('TabHromadneProEMailDef',)
('TabSzPlemeno',)
('TabIdentKartaOrg',)
('TabPTVKatLeas',)
('TabFIAAVSegmentVykazParam',)
('TabAutomatizace',)
('TabUzivStrom',)
('TabAutomatNavaznyPrehled',)
('TabZkVypocetRezie',)
('TabMaFaZboziTxtPol',)
('TabMzIspvCzZam',)
('TabSzStado',)
('ASGs_Browse',)
('TabPrPostup',)
('TabPluginInfo',)
('Gatema_SDMapaSkl',)
('TabIkony',)
('TabIPHMCerpTyp',)
('TabDosleObjTxtPol01',)
('TabFIAVDataDimPrvekKmenZbozi',)
('TabNCTSZajdlko',)
('TabSluzbyMOSSCisUct',)
('TabUniImportKmenFormat',)
('TabMzExekuceSk',)
('TabMaDot',)
('TabIPozRadDispon',)
('TabPravaExtKom',)
('TabRezie',)
('TabFormaUhrady',)
('TabFIAWebObjects',)
('TabDanoveKlice',)
('TabDefISPMS',)
('TabDzPPoNavaznyPrehledVzor',)
('TabVKonJedVyrPlan',)
('TabVStromDORada',)
('ASGs_Vazby',)
('TabGprUlohyPerZdroje',)
('TabKontaktyImp',)
('TabEvidRozpracOperProstoje',)
('TabSkupRegDPH',)
('TabPTVVarLeas',)
('TabMzdPojMes',)
('TabFIAAVUtvarVykazParam',)
('TabMzdOdpPolRok',)
('TabCelSazSZ',)
('TabFIAADefVykazParamVykazDefinice',)
('TabMaFaPrZa',)
('TabObsazeniPracovnichPozic',)
('TabNotifikaceSeznamID',)
('TabPokladnaZaloha',)
('Tabx_VSDMesVypocet',)
('TabVPenTokPokl',)
('TabEMailText',)
('TabMaFaZboziDoklady',)
('TabDavkaImp',)
('TabMzDefRozpadMS',)
('TabKontrKapacPlan',)
('TabAVAReceivedInvoiceFiles',)
('TabPersOrgChart',)
('TabUkolZam',)
('TabSzKoefPrirust',)
('TabZeFATypDokladu',)
('Gatema_SDVykrytePozNaZmenuUm',)
('TabDefTabUzivConstraint',)
('TabDruhDZSalSk',)
('TabSaldoArchCM',)
('TabMaUS',)
('TabKZam',)
('TabFIADataParamPohled',)
('TabPrednaPozn',)
('TabMaUctyTypPohKonfig',)
('TabOpravnaAkceStavSkladu_Log',)
('TabDSPrepocetMnozstvi',)
('TabMzdOdpPolMS',)
('TabWFKonfig',)
('TabVyporadaniCZ15',)
('TabFIAPreuctovaniReziiSkupina',)
('TabZakazkaRada',)
('TabGprVazbyDoVyroby',)
('TabMzSocFond',)
('TabMzKontoPD',)
('TabPokladnaImp',)
('TabGDPRPozadavkySubjekty',)
('TabPlanKalendare',)
('TabQMSKlasPravdepodOdhalVady',)
('TabSTDDenikPoznamka',)
('TabPTVPTUcto',)
('TabJCDDokTyp',)
('TabESServicePrints',)
('TabMOSSKurzy',)
('TabKurzList',)
('TabFIAAVZakazkaVykazParam',)
('TabGDPRAtribut',)
('TabPohybyZbozi_SS_Log',)
('TabSkoliciAkceR',)
('TabBankVypisR',)
('TabPenFakPolozky',)
('TabMzIspCzAtr',)
('TabRozkopGK',)
('TabNotifikaceSum',)
('TabZkVypocetUkazatelu',)
('TabExtHlasky',)
('TabCelUra',)
('TabMzImpDefUP',)
('TabMzExportPDS',)
('TabMaFaSablonyPrZa',)
('TabObdobiStavu',)
('TabAutoImpKLDB',)
('TabMzPrilohyKDatu',)
('TabIPHMCerpani',)
('TabFIADataPohledAkt',)
('TabSvsPredmet2',)
('TabPrikazP',)
('TabMzHlaseniDohod',)
('TabPravaDruhPok',)
('TabFIADataParam',)
('TabUmistLog',)
('TabSzKonstanty',)
('TabDosleObjNavazTxt02',)
('Gatema_SDUmisteniPolDokladuOZ',)
('TabFiaWebScripts',)
('TabPravaKategorieKJ',)
('TabPlanPrikaz',)
('TabOZDifDSNMnoz',)
('TabHGlob',)
('TabFIAASouctyText',)
('TabUniImportSort',)
('TabDokumenty',)
('TabAkceZakazOrg',)
('TabZpusobZajDObj03',)
('TabURLKL',)
('TabSTDUctovyRozvrhStandardDistr',)
('TabVObdObdDPH',)
('TabKategPlneniUkolu',)
('TabDochazkaObecne',)
('TabNotifikaceRegistr',)
('TabMzDvzUdajeImp',)
('TabDosleObjNavazDok02',)
('TabFIAAVykazSkupina',)
('TabDzPPoNavaznyPrehled',)
('TabAVAReceivedInvoiceHeader',)
('TabSlOrgImp',)
('TabZajistX03',)
('TabVyporadaniCZ25',)
('TabUniImportKmenUp',)
('Tabx_VZDPrehledPlateb',)
('TabOLAP',)
('TabIntrMonthMsg',)
('TabMzdPojRok',)
('TabFIAStavUctu',)
('TabMzdTar',)
('TabMzSadyStrav',)
('TabSTDZurnal',)
('TabVztahOrgKOs',)
('TabNCTSZajOzn',)
('TabEvListDZ',)
('TabMzPodpDobaProdl',)
('TabPrjPerSRC',)
('TabZajisteniDPHWSLog',)
('TabFormaDopravy',)
('TabMzENeschPobytSk',)
('TabVyporadaniSK406',)
('dtproperties',)
('TabMaPrRU',)
('TabFIAUkazatelStrom',)
('TabGprZavislostiUloh',)
('TabMzIsp2014CzMS',)
('TabVyrCisPrKV',)
('TabFIAAReportHodn',)
('TabCelZaruky',)
('TabIkonyProAkce',)
('TabFIADataParamPohledPrava',)
('TabJCDDokTypVAZ',)
('TabFIAAStavUctu',)
('TabUniImportSortVerze',)
('TabMzdDanSk',)
('TabVDSPrepocetMnozstvi',)
('TabMzDruhyPPMS',)
('TabZkVypocetUkazateluKonstanty',)
('TabFIAUkazatelDefiniceVysledek',)
('TabPravaGenMzdyH',)
('TabMzDefRozpadZam',)
('Gatema_SDPovoleneSklady',)
('TabUniImportMzdyVerze',)
('TabMzPocHod',)
('TabPTVVarUcto',)
('TabFIAEIntecomp',)
('Gatema_PohybManJedStruk',)
('TabPrjSazbyTasks',)
('TabAutomatizacePodminky',)
('TabMzdOdpPolMzd',)
('TabPSC',)
('TabFIAWebs',)
('TabNavazDokFak',)
('TabNCTSDokTypVAZDokumVAZ',)
('TabPersOrgChartDetail',)
('TabFIAAVReportVykazParam',)
('TabPoznOrgImp',)
('TabSaldoDenPrehCM',)
('TabMzPrilohyKDatuRO',)
('TabSTDSbornik',)
('TabFIAESkupinyIntercomp',)
('TabInvPolozkaData',)
('TabPlatbaPresTerminal',)
('TabPenTokDoklady',)
('TabVObecPrKontakty',)
('TabFIAAVUtvarVykazParamVykazDefinice',)
('TabWFLog',)
('TabCelZarukyCerpani',)
('TabSlZboImp',)
('TabPersOrgChartNodes',)
('TabSOZNaCeny',)
('TabIVozCenUroven',)
('TabCisMzSlDistrLog',)
('Gatema_SDOZKonfig',)
('TabIkonyProSoudky',)
('TabIKod2DPH',)
('TabFIAVSestavaUkazatel',)
('TabIVozAlarm',)
('TabGrafTeeChart',)
('TabDICOrgArch',)
('TabUniImportSortFormat',)
('TabGDPRTridyDat',)
('TabJCDFa',)
('TabPerSlozDef',)
('TabInvVyrobyPrikazy',)
('TabAkceZakazRadaU',)
('TabVaPlan',)
('TabFIAAVObdobiProVykazyObdobiStavu',)
('TabAVAReceivedInvoiceAdvancePayments',)
('TabMzIsp2014CzOrg',)
('TabUctenkaRFin',)
('TabSzStavSkladu',)
('TabPersVyberRizeni',)
('TabGprUlohyMatZdroje',)
('TabGDPRPozadavkyZaznamy',)
('TabPlanKalendPol',)
('TabAutoImpKLDny',)
('TabUniImportMzdyFormat',)
('TabPlanPrikazP',)
('Gatema_PohybManJedPolOZ',)
('TabLastSetting',)
('TabDokumVazba',)
('TabMzOpravyDanBon',)
('TabCisOrgArch',)
('TabFIAAVZakazkaVykazParamVykazDefinice',)
('TabPodkladKFak',)
('TabSchvalovaciRole',)
('TabZamPer',)
('TabZkVysledovka',)
('TabFakturyPrehledy',)
('Tabx_VZDMesVypocet',)
('TabICestDT',)
('TabDosleObjNavazTxt03',)
('TabZeFAFormaUhrady',)
('TabQMSDalsiParHodn',)
('TabBodoveKontoOrg',)
('TabIPneumatika',)
('TabNCTSZavtra',)
('TabDenikKurz',)
('TabEETKomXML',)
('TabFIAAVNakladovyOkruhVykazParam',)
('TabISDObd',)
('TabDSZadrzovanaSD',)
('TabIntrMonthMsgPohybyZdroj',)
('TabFIAVStornoPreuct',)
('TabICOPAP',)
('TabCisOrg',)
('TabFIAVWebDatabase',)
('TabGprLogTerminyCastky',)
('TabDosleObjNavazDok03',)
('TabFIAAKontrolniVazby',)
('TabISBSM',)
('TabMzKontoPDZmeny',)
('TabFIACVUtvarVykazParamPlanDef',)
('TabPlanKalendSv',)
('TabFIAVSestavaObdobiZobrazeni',)
('TabDosleObjRekapDPH01',)
('TabVKonJedKmenZbozi',)
('TabMzdPoj',)
('TabTypyZmenDef',)
('TabPrikazMzdyAZmetkyNaradi',)
('TabZpusobZajKry01',)
('TabSDPH',)
('TabFIAAVNakOkruhVykazParamVykazDefinice',)
('TabVKontaSkupKontKO',)
('TabKalZamKOs',)
('TabGprVzorZavislostiUloh',)
('TabDruhDokZboImp',)
('TabVVarPTSal',)
('TabICestDZ',)
('TabCisUcSalSkImp',)
('TabIkonyProPrehledy',)
('TabDashboard',)
('TabBodoveKontoUprava',)
('TabIPneuHist',)
('TabSzPolozkyCRZ',)
('Gatema_PozNaZmenuUm',)
('TabPrikazNaOpravu',)
('TabDuchVek',)
('TabPrjResitele',)
('TabFIAAPrehledKontrola',)
('TabUniImportOZ',)
('TabGDPRTridyDatPolozky',)
('TabDefPlatPrik',)
('TabCastiKHDanKlice',)
('TabDenKR',)
('TabMzIspCzMS',)
('TabKmenZbozi_EXT',)
('TabFIAWebAppStruct',)
('TabVKonJedDosleObj',)
('TabObaly',)
('TabMzdObd',)
('TabCakoCisPop',)
('TabGraphDef',)
('TabIZasilkaNV',)
('TabEvPSchrankyDefForm',)
('TabMaPrZa',)
('TabFIACVZakazkaVykazParamPlanDef',)
('TabVATIDPravidlaVyjimky',)
('TabFIAVUkazatelUtvary',)
('TabUniImportDVZ',)
('TabSkladDruhDok',)
('TabPravaDefZprav',)
('TabFIAEVSkupinyIntercompPolozkyKonsVykazu',)
('TabStromImp',)
('TabCSUISSchranky',)
('TabKodMen',)
('TabAkcePoklProdPol',)
('TabOZKolekce',)
('TabFIAPreuctovaniReziiPom',)
('TabFIAAVVozidloVykazParamVykazDefinice',)
('TabKontaKOM',)
('TabKontrolyEkoIDs',)
('TabZkVarianty',)
('TabAVAReceivedInvoiceItem',)
('TabNCTSPohybyVINCodes',)
('TabVKatPTSal',)
('TabEETKomunikace',)
('TabZajistKryX03',)"""